name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust nightly
      run: |
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly

    - name: Build
      run: |
        set RUSTFLAGS="-Zlocation-detail=none"
        cargo +nightly build -Z build-std=std,panic_abort --target x86_64-pc-windows-msvc --release

    - uses: actions/upload-artifact@v4
      with:
        name: windows
        path: |
          target/*/release/bob_diff.lib

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly
      run: |
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly

    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none" cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --release

    - uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          target/*/release/libbob_diff.a

  publish:
    runs-on: ubuntu-latest
    needs: [windows, linux]
    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./**/*
          bob_diff.h
        generate_release_notes: true
        body: |
          Pre-built Windows & Linux files
  
